services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: feuerwehr-backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: feuerwehr-frontend:latest