# database connection
spring.datasource.url=jdbc:postgresql://${DATABASE_IP}:${DATABASE_PORT}/{DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
# better performance and scalability (search Open Session In View)
spring.jpa.open-in-view=false
